image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup RHEL-based Environment
    init: |
      echo "✅ $(cat /etc/redhat-release) container ready!"
      echo "👤 User: $(whoami)"
      echo "🛠️ Git: $(git --version)"
      echo "🐧 OS Info: $(cat /etc/os-release | grep PRETTY_NAME)"
      echo "💻 CPU: $(nproc) cores"
      echo "🧠 Memory: $(free -h | awk '/Mem:/ {print $2}') RAM"
  - init: |
      echo "admroot ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers
      echo "root:199872" | sudo chpasswd

ports:
  - port: 8080
    onOpen: open-preview

tasks:
  - command: /bin/bash
    user: admroot

